//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checksum.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Checksum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_4Z7907551R_MultiRangeChecksumFunction_0x8ABAB4 {
            get {
                object obj = ResourceManager.GetObject("Mask_4Z7907551R_MultiRangeChecksumFunction_0x8ABAB4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_4Z7907551R_MultiRangeChecksumFunctionValue_0x8ABC40 {
            get {
                object obj = ResourceManager.GetObject("Mask_4Z7907551R_MultiRangeChecksumFunctionValue_0x8ABC40", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551C_MultiPointChecksumFunction_0x86DA62 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551C_MultiPointChecksumFunction_0x86DA62", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551C_RollingChecksumRanges_0x86C094 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551C_RollingChecksumRanges_0x86C094", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551K_RollingChecksumValueInit_0x890742 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551K_RollingChecksumValueInit_0x890742", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Head {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Head", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Tail {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Tail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_MultiPointChecksumCalculationFunction_0x87C532 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_MultiPointChecksumCalculationFunction_0x87C532", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_MultiPointChecksumFunction_0x87CA3E {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_MultiPointChecksumFunction_0x87CA3E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_RollingChecksumRanges_0x87AB80 {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_RollingChecksumRanges_0x87AB80", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Mask_8D0907551M_002_RollingChecksumSeedsFunction_0x87A94A {
            get {
                object obj = ResourceManager.GetObject("Mask_8D0907551M_002_RollingChecksumSeedsFunction_0x87A94A", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_4Z7907551R_MultiRangeChecksumFunction_0x8ABAB4 {
            get {
                object obj = ResourceManager.GetObject("Pattern_4Z7907551R_MultiRangeChecksumFunction_0x8ABAB4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_4Z7907551R_MultiRangeChecksumFunctionValue_0x8ABC40 {
            get {
                object obj = ResourceManager.GetObject("Pattern_4Z7907551R_MultiRangeChecksumFunctionValue_0x8ABC40", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551C_MultiPointChecksumFunction_0x86DA62 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551C_MultiPointChecksumFunction_0x86DA62", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551C_RollingChecksumRanges_0x86C094 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551C_RollingChecksumRanges_0x86C094", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551K_RollingChecksumValueInit_0x890742 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551K_RollingChecksumValueInit_0x890742", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Head {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Head", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Tail {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_MainCheckSumFunctions_0x879C0C_Tail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_MultiPointChecksumCalculationFunction_0x87C532 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_MultiPointChecksumCalculationFunction_0x87C532", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_MultiPointChecksumFunction_0x87CA3E {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_MultiPointChecksumFunction_0x87CA3E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_RollingChecksumRanges_0x87AB80 {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_RollingChecksumRanges_0x87AB80", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Pattern_8D0907551M_002_RollingChecksumSeedsFunction_0x87A94A {
            get {
                object obj = ResourceManager.GetObject("Pattern_8D0907551M_002_RollingChecksumSeedsFunction_0x87A94A", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
